[project]
authors = [
    {name = "Qinyu Luo", email = "qinyuluo123@gmail.com"},
]
maintainers = [
    {name = "Arno Edwards", email = "Arno.Edwards@outlook.com"},
]
license = {text = "Apache-2.0"}
requires-python = ">=3.10,<4.0"
dependencies = [
    "gitpython<4.0.0,>=3.1.41",
    "openai<2.0.0,>=1.6.1",
    "tiktoken<1.0.0,>=0.5.2",
    "pyyaml<7.0.0,>=6.0.1",
    "jedi<1.0.0,>=0.19.1",
    "loguru<1.0.0,>=0.7.2",
    "click<9.0.0,>=8.1.7",
    "tomlkit<1.0.0,>=0.12.3",
    "pydantic-settings<3.0.0,>=2.1.0",
    "python-iso639<2025.0.0,>=2024.1.2",
    "tenacity<9.0.0,>=8.2.3",
    "colorama>=0.4.6",
]
name = "repoagent"
version = "0.0.6"
description = "An Agent designed to offer an intelligent approach for generating project documentation."
readme = "README.md"

[project.urls]
repository = "https://github.com/LOGIC-10/RepoAgent"

[project.scripts]
repoagent = "repo_agent.main:app"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest<8.0.0,>=7.4.4",
    "pytest-mock<4.0.0,>=3.12.0",
]

[tool.pdm.build]
includes = [
    "repo_agent",
]


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

